CREATE TABLE Members (
    UserId INT,
    ChatId INT,
    PRIMARY KEY(UserId, ChatId),
    FOREIGN KEY (UserId) REFERENCES Users(UserId) ON DELETE CASCADE,
    FOREIGN KEY (ChatId) REFERENCES Chats(ChatId) ON DELETE CASCADE
);
