CREATE TABLE Users (
    UserId INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Avatar VARCHAR(255) NOT NULL,
    Bio TEXT NOT NULL,
    LastSeen TIMESTAMP,
    IsActivePrivacy BOOLEAN DEFAULT 0,
    IsLastSeenPrivacy BOOLEAn DEFAULT 0
);
